# Generated by Django 4.2.1 on 2023-06-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_img', models.ImageField(upload_to='games')),
                ('g_title', models.CharField(max_length=100)),
                ('g_description', models.CharField(max_length=500)),
            ],
        ),
    ]
