# Generated by Django 4.2.1 on 2023-06-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_desktop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_img', models.ImageField(upload_to='./lp/')),
                ('l_title', models.CharField(max_length=100)),
                ('l_description', models.CharField(max_length=500)),
                ('l_price', models.IntegerField()),
            ],
        ),
    ]
