# Generated by Django 4.2.1 on 2023-06-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_accessorie_stock_component_stock_desktop_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='./games/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('stock', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Game3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='./games/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('stock', models.IntegerField(default=10)),
            ],
        ),
    ]
