# Generated by Django 4.2.1 on 2023-06-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_desktop1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('l_img', models.ImageField(upload_to='./lp/')),
                ('l_title', models.CharField(max_length=100)),
                ('l_description', models.CharField(max_length=500)),
                ('l_price', models.IntegerField()),
                ('stock', models.IntegerField(default=10)),
            ],
        ),
    ]
