# Generated by Django 4.2.1 on 2023-06-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_laptop2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gadget2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='./g/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField(default=10)),
            ],
        ),
    ]
