# Generated by Django 4.2.1 on 2023-06-08 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_accessorie2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessorie2',
        ),
    ]
